version: '3.8'

services:
  nginx:
    # FIXED: Added build context instead of using image
    build:
      context: ./nginx
    # FIXED: Changed "eighty:80" to "80:80"
    ports:
      - "80:80"
    # FIXED: Corrected config file path (removed 'i' from 'nginx.confi')
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-network
    # FIXED: Added depends_on to ensure Python app starts first
    depends_on:
      - python-app

  python-app:
    # FIXED: Added build context instead of using image
    build:
      context: ./python
    container_name: python_app
    # FIXED: Changed "eight thousand" to "8000"
    expose:
      - "8000"
    networks:
      - nginx-network

networks:
  nginx-network:
    # FIXED: Removed typo in 'bridge' (was 'bridg')
    driver: bridge
    # FIXED: Removed unnecessary complex options
   